version: '3'
services:
  test-db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    volumes:
      - ./testdata:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
